version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: PST8PDT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.0
    - 12.6.2
  - dependency-name: flow-bin
    versions:
    - 0.141.0
    - 0.143.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  rebase-strategy: disabled
